#!/bin/sh
# parameters are passed via environment variables:
# CIRCLECI_TOKEN
# PROJECT
# BRANCH
# TRIGGER_NAME
#
# see app.json for details.

if [ -z "$CIRCLECI_TOKEN" ] ; then
    echo No CIRCLECI_TOKEN is set.
    exit
fi

api_prefix=https://circleci.com/api/v1/project/
trigger_build_url="${api_prefix}/${PROJECT}/tree/${BRANCH}?circle-token=${CIRCLECI_TOKEN}"
payload="{ \"build_parameters\": { \"${TRIGGER_NAME}\": \"true\" } }"

curl \
  --header "Accept: application/json" \
  --header "Content-Type: application/json" \
  --header "User-Agent: build-circleci/1.0"
  --data "${payload}" \
  --request POST ${trigger_build_url}